### ISSUE TITLE
How to get an image with layer blending mode?

### ISSUE THREAD

**Issue by ironxu** [TheNicker/libpsd#1]
this is my code

> psd_context* context = NULL;
> psd_status status = psd_image_load(&context, "D:\\test.psd");
> psd_short layer_count = context->layer_count;
> for (size_t i = 0; i < layer_count; i++)
> {
> 	psd_layer_record record = context->layer_records[i];
> 	unsigned int *image_data_ = NULL;
> 	unsigned long image_data_length_ = NULL;
> 	unsigned long num_bytes = record.width * record.height * 4;
> 	unsigned int *buf = record.image_data;
> 
> 	image_data_ = new unsigned int[num_bytes];
> 	image_data_length_ = num_bytes / 4;
> 	memcpy(image_data_, buf, num_bytes);
>  	/*write to file code*/
>  	/*...*/
> }
> psd_image_free(context);
> 

I use '**psd_image_blend**', but it doesn't seem to work. Can you tell me how to get a blending layer?

**Comment by TheNicker** [comment]
I'm not sure if this is your case but there's an open bug for 'psd_image_blend'
https://sourceforge.net/p/libpsd/bugs/1/

I use this library only for the merged image and I haven't test it for any other use case.
https://github.com/OpenImageViewer/OIV/blob/master/ImageCodec/Codecs/CodecPSD/Source/CodecPSD.h

Contribution to the codebase is welcomed.
